name: Multi node test workflow

# This workflow is triggered on pull requests to master
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    # Job name
    name: Build Asynchronous Search
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.java }}
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Run integration tests with multi node config
        run: |
          ./gradlew integTest -PnumNodes=5
      - name: Run Backwards Compatibility Tests
        run: |
          echo "Running backwards compatibility tests ..."
          ./gradlew bwcTestSuite -Dtests.security.manager=false
      - name: Upload failed logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: build/testclusters/integTest-*/logs/*
